# Generated by Django 4.2.4 on 2023-09-06 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0005_alter_review_user'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking_item',
            new_name='BookingItem',
        ),
    ]
