# Generated by Django 4.2.4 on 2023-09-07 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0005_alter_review_user'),
        ('booking', '0003_bookingitem_user_alter_bookingitem_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingitem',
            name='hostel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.hotel'),
        ),
    ]
